// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(rust_coreFFI)
import rust_coreFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_rust_core_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_rust_core_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureRustCoreInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
// Initial value and increment amount for handles. 
// These ensure that SWIFT handles always have the lowest bit set
fileprivate let UNIFFI_HANDLEMAP_INITIAL: UInt64 = 1
fileprivate let UNIFFI_HANDLEMAP_DELTA: UInt64 = 2

fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = UNIFFI_HANDLEMAP_INITIAL

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            return doInsert(obj)
        }
    }

    // Low-level insert function, this assumes `lock` is held.
    private func doInsert(_ obj: T) -> UInt64 {
        let handle = currentHandle
        currentHandle += UNIFFI_HANDLEMAP_DELTA
        map[handle] = obj
        return handle
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

     func clone(handle: UInt64) throws -> UInt64 {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return doInsert(obj)
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterInt32: FfiConverterPrimitive {
    typealias FfiType = Int32
    typealias SwiftType = Int32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Int32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Int32, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterInt64: FfiConverterPrimitive {
    typealias FfiType = Int64
    typealias SwiftType = Int64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Int64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Int64, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}


/**
 * Result type for file operations
 */
public struct FileOpResult: Equatable, Hashable {
    public var success: Bool
    public var message: String
    public var affectedCount: Int32

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(success: Bool, message: String, affectedCount: Int32) {
        self.success = success
        self.message = message
        self.affectedCount = affectedCount
    }

    
}

#if compiler(>=6)
extension FileOpResult: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFileOpResult: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FileOpResult {
        return
            try FileOpResult(
                success: FfiConverterBool.read(from: &buf), 
                message: FfiConverterString.read(from: &buf), 
                affectedCount: FfiConverterInt32.read(from: &buf)
        )
    }

    public static func write(_ value: FileOpResult, into buf: inout [UInt8]) {
        FfiConverterBool.write(value.success, into: &buf)
        FfiConverterString.write(value.message, into: &buf)
        FfiConverterInt32.write(value.affectedCount, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFileOpResult_lift(_ buf: RustBuffer) throws -> FileOpResult {
    return try FfiConverterTypeFileOpResult.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFileOpResult_lower(_ value: FileOpResult) -> RustBuffer {
    return FfiConverterTypeFileOpResult.lower(value)
}


/**
 * Outcome of changing the folder list, so the UI can report what happened
 * instead of silently succeeding.
 */
public struct FolderUpdate: Equatable, Hashable {
    public var accepted: [String]
    public var rejected: [String]
    /**
     * Rows dropped because they no longer sit under any indexed folder.
     */
    public var pruned: UInt32

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(accepted: [String], rejected: [String], 
        /**
         * Rows dropped because they no longer sit under any indexed folder.
         */pruned: UInt32) {
        self.accepted = accepted
        self.rejected = rejected
        self.pruned = pruned
    }

    
}

#if compiler(>=6)
extension FolderUpdate: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFolderUpdate: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FolderUpdate {
        return
            try FolderUpdate(
                accepted: FfiConverterSequenceString.read(from: &buf), 
                rejected: FfiConverterSequenceString.read(from: &buf), 
                pruned: FfiConverterUInt32.read(from: &buf)
        )
    }

    public static func write(_ value: FolderUpdate, into buf: inout [UInt8]) {
        FfiConverterSequenceString.write(value.accepted, into: &buf)
        FfiConverterSequenceString.write(value.rejected, into: &buf)
        FfiConverterUInt32.write(value.pruned, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFolderUpdate_lift(_ buf: RustBuffer) throws -> FolderUpdate {
    return try FfiConverterTypeFolderUpdate.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFolderUpdate_lower(_ value: FolderUpdate) -> RustBuffer {
    return FfiConverterTypeFolderUpdate.lower(value)
}


/**
 * What one incremental pass changed. Returned so the UI can skip a refresh
 * when nothing actually moved.
 */
public struct IndexUpdate: Equatable, Hashable {
    public var upserted: UInt32
    public var removed: UInt32

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(upserted: UInt32, removed: UInt32) {
        self.upserted = upserted
        self.removed = removed
    }

    
}

#if compiler(>=6)
extension IndexUpdate: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeIndexUpdate: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> IndexUpdate {
        return
            try IndexUpdate(
                upserted: FfiConverterUInt32.read(from: &buf), 
                removed: FfiConverterUInt32.read(from: &buf)
        )
    }

    public static func write(_ value: IndexUpdate, into buf: inout [UInt8]) {
        FfiConverterUInt32.write(value.upserted, into: &buf)
        FfiConverterUInt32.write(value.removed, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeIndexUpdate_lift(_ buf: RustBuffer) throws -> IndexUpdate {
    return try FfiConverterTypeIndexUpdate.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeIndexUpdate_lower(_ value: IndexUpdate) -> RustBuffer {
    return FfiConverterTypeIndexUpdate.lower(value)
}


public struct SearchResult: Equatable, Hashable {
    public var fileName: String
    public var filePath: String
    public var fileSize: UInt64
    public var isFolder: Bool
    public var score: Int64
    public var dateValue: Int64
    public var dateKind: String
    public var fileKind: String
    public var prettyDate: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(fileName: String, filePath: String, fileSize: UInt64, isFolder: Bool, score: Int64, dateValue: Int64, dateKind: String, fileKind: String, prettyDate: String) {
        self.fileName = fileName
        self.filePath = filePath
        self.fileSize = fileSize
        self.isFolder = isFolder
        self.score = score
        self.dateValue = dateValue
        self.dateKind = dateKind
        self.fileKind = fileKind
        self.prettyDate = prettyDate
    }

    
}

#if compiler(>=6)
extension SearchResult: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSearchResult: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SearchResult {
        return
            try SearchResult(
                fileName: FfiConverterString.read(from: &buf), 
                filePath: FfiConverterString.read(from: &buf), 
                fileSize: FfiConverterUInt64.read(from: &buf), 
                isFolder: FfiConverterBool.read(from: &buf), 
                score: FfiConverterInt64.read(from: &buf), 
                dateValue: FfiConverterInt64.read(from: &buf), 
                dateKind: FfiConverterString.read(from: &buf), 
                fileKind: FfiConverterString.read(from: &buf), 
                prettyDate: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: SearchResult, into buf: inout [UInt8]) {
        FfiConverterString.write(value.fileName, into: &buf)
        FfiConverterString.write(value.filePath, into: &buf)
        FfiConverterUInt64.write(value.fileSize, into: &buf)
        FfiConverterBool.write(value.isFolder, into: &buf)
        FfiConverterInt64.write(value.score, into: &buf)
        FfiConverterInt64.write(value.dateValue, into: &buf)
        FfiConverterString.write(value.dateKind, into: &buf)
        FfiConverterString.write(value.fileKind, into: &buf)
        FfiConverterString.write(value.prettyDate, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSearchResult_lift(_ buf: RustBuffer) throws -> SearchResult {
    return try FfiConverterTypeSearchResult.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSearchResult_lower(_ value: SearchResult) -> RustBuffer {
    return FfiConverterTypeSearchResult.lower(value)
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * Which timestamp drives sorting, filtering and the date column.
 *
 * `Either` is the historical behaviour: show whichever of the two is more
 * recent. It's a reasonable default for "what did I touch lately" and a
 * terrible one for "what landed here last week", which is why the other two
 * exist and why the choice is the caller's.
 *
 * Caveat worth knowing: `Added` is birthtime, i.e. when the file was created.
 * Finder's "Date Added" column is `kMDItemDateAdded` — when the file arrived
 * in *that folder* — which differs for anything moved after creation. Closing
 * that gap means pulling Spotlight metadata into `file_signals`; birthtime is
 * the honest approximation until then.
 */

public enum DateField: Equatable, Hashable {
    
    case added
    case modified
    case either



}

#if compiler(>=6)
extension DateField: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeDateField: FfiConverterRustBuffer {
    typealias SwiftType = DateField

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> DateField {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .added
        
        case 2: return .modified
        
        case 3: return .either
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: DateField, into buf: inout [UInt8]) {
        switch value {
        
        
        case .added:
            writeInt(&buf, Int32(1))
        
        
        case .modified:
            writeInt(&buf, Int32(2))
        
        
        case .either:
            writeInt(&buf, Int32(3))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDateField_lift(_ buf: RustBuffer) throws -> DateField {
    return try FfiConverterTypeDateField.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDateField_lower(_ value: DateField) -> RustBuffer {
    return FfiConverterTypeDateField.lower(value)
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterString.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeSearchResult: FfiConverterRustBuffer {
    typealias SwiftType = [SearchResult]

    public static func write(_ value: [SearchResult], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeSearchResult.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [SearchResult] {
        let len: Int32 = try readInt(&buf)
        var seq = [SearchResult]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeSearchResult.read(from: &buf))
        }
        return seq
    }
}
/**
 * Returns true if there is at least one reversible block that hasn't been
 * undone — the Swift menu uses this to enable/disable the Cmd+Z menu item.
 */
public func canUndo() -> Bool  {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_rust_core_fn_func_can_undo($0
    )
})
}
/**
 * Compress files into a ZIP archive
 */
public func compressFiles(paths: [String], archivePath: String) -> FileOpResult  {
    return try!  FfiConverterTypeFileOpResult_lift(try! rustCall() {
    uniffi_rust_core_fn_func_compress_files(
        FfiConverterSequenceString.lower(paths),
        FfiConverterString.lower(archivePath),$0
    )
})
}
/**
 * Copy files to a destination folder
 */
public func copyFiles(sourcePaths: [String], destination: String) -> FileOpResult  {
    return try!  FfiConverterTypeFileOpResult_lift(try! rustCall() {
    uniffi_rust_core_fn_func_copy_files(
        FfiConverterSequenceString.lower(sourcePaths),
        FfiConverterString.lower(destination),$0
    )
})
}
/**
 * Create a new folder
 */
public func createFolder(path: String) -> FileOpResult  {
    return try!  FfiConverterTypeFileOpResult_lift(try! rustCall() {
    uniffi_rust_core_fn_func_create_folder(
        FfiConverterString.lower(path),$0
    )
})
}
/**
 * Get a compact file listing for AI context (saves tokens)
 */
public func getFileListingForAi(path: String) -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_rust_core_fn_func_get_file_listing_for_ai(
        FfiConverterString.lower(path),$0
    )
})
}
/**
 * Folders currently indexed. This is the real list the indexer uses — the
 * Settings UI reads it from here rather than keeping its own copy, which is
 * how it ended up displaying three folders it had no influence over.
 */
public func getIndexedFolders() -> [String]  {
    return try!  FfiConverterSequenceString.lift(try! rustCall() {
    uniffi_rust_core_fn_func_get_indexed_folders($0
    )
})
}
/**
 * Recent files by the selected date field.
 *
 * `within_days` bounds the window; 0 means "no lower bound", which is what
 * makes "everything by date added" answerable rather than silently capped.
 */
public func getRecentFiles(dateField: DateField, withinDays: UInt32) -> [SearchResult]  {
    return try!  FfiConverterSequenceTypeSearchResult.lift(try! rustCall() {
    uniffi_rust_core_fn_func_get_recent_files(
        FfiConverterTypeDateField_lower(dateField),
        FfiConverterUInt32.lower(withinDays),$0
    )
})
}
/**
 * Reconcile the index against a specific set of paths, as reported by
 * FSEvents. This is the steady-state path: it touches only what changed
 * instead of re-walking every scan root.
 *
 * For each path:
 * - gone from disk → delete its row, plus every row beneath it (a deleted
 * or renamed directory takes its whole subtree with it)
 * - a directory → re-walk that subtree and tombstone-prune it, which also
 * covers the coalesced `MustScanSubDirs` events FSEvents sends under load
 * - a file → upsert if indexable, otherwise make sure it isn't lingering
 *
 * Paths outside the scan roots are ignored, so the caller can forward the
 * raw event list without pre-filtering.
 */
public func indexPaths(paths: [String]) -> IndexUpdate  {
    return try!  FfiConverterTypeIndexUpdate_lift(try! rustCall() {
    uniffi_rust_core_fn_func_index_paths(
        FfiConverterSequenceString.lower(paths),$0
    )
})
}
/**
 * Last FSEvents id we have already folded into the index, or 0 if none.
 * The app passes this back as the stream's `sinceWhen` so a relaunch replays
 * only what changed while it was closed instead of re-walking everything.
 */
public func lastEventId() -> UInt64  {
    return try!  FfiConverterUInt64.lift(try! rustCall() {
    uniffi_rust_core_fn_func_last_event_id($0
    )
})
}
/**
 * Load the persisted index for instant startup.
 * Returns rows ordered by the selected date desc; capped to 50k to keep the
 * FFI crossing cheap. If the DB isn't openable yet, returns [].
 */
public func loadCachedIndex(dateField: DateField) -> [SearchResult]  {
    return try!  FfiConverterSequenceTypeSearchResult.lift(try! rustCall() {
    uniffi_rust_core_fn_func_load_cached_index(
        FfiConverterTypeDateField_lower(dateField),$0
    )
})
}
/**
 * Move files to a destination folder
 */
public func moveFiles(sourcePaths: [String], destination: String) -> FileOpResult  {
    return try!  FfiConverterTypeFileOpResult_lift(try! rustCall() {
    uniffi_rust_core_fn_func_move_files(
        FfiConverterSequenceString.lower(sourcePaths),
        FfiConverterString.lower(destination),$0
    )
})
}
/**
 * True when the app should run a full `rebuild_index` instead of relying on
 * the incremental stream: nothing indexed yet, or the last full scan is old
 * enough that we can't trust having seen every event since.
 */
public func needsFullRescan() -> Bool  {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_rust_core_fn_func_needs_full_rescan($0
    )
})
}
/**
 * Full rescan of every scan root. Expensive: this walks the whole tree, so
 * the app should call it on first run or when the incremental event stream
 * has gone stale — `index_paths` handles the steady state.
 */
public func rebuildIndex() -> [SearchResult]  {
    return try!  FfiConverterSequenceTypeSearchResult.lift(try! rustCall() {
    uniffi_rust_core_fn_func_rebuild_index($0
    )
})
}
/**
 * Rename a file. `new_name` must be a basename (no `/`, no `..`).
 */
public func renameFile(path: String, newName: String) -> FileOpResult  {
    return try!  FfiConverterTypeFileOpResult_lift(try! rustCall() {
    uniffi_rust_core_fn_func_rename_file(
        FfiConverterString.lower(path),
        FfiConverterString.lower(newName),$0
    )
})
}
public func searchFiles(query: String, dateField: DateField) -> [SearchResult]  {
    return try!  FfiConverterSequenceTypeSearchResult.lift(try! rustCall() {
    uniffi_rust_core_fn_func_search_files(
        FfiConverterString.lower(query),
        FfiConverterTypeDateField_lower(dateField),$0
    )
})
}
/**
 * Replace the indexed-folder list.
 *
 * Rejects anything that isn't an existing directory or that `safety` refuses
 * as a read root, and reports it rather than failing the whole call — one bad
 * entry shouldn't discard the user's other choices.
 *
 * Rows outside the new roots are pruned immediately, and the full-scan stamp
 * is cleared so the caller's next `needs_full_rescan` returns true: widening
 * the roots means there is now content we've never walked.
 */
public func setIndexedFolders(folders: [String]) -> FolderUpdate  {
    return try!  FfiConverterTypeFolderUpdate_lift(try! rustCall() {
    uniffi_rust_core_fn_func_set_indexed_folders(
        FfiConverterSequenceString.lower(folders),$0
    )
})
}
/**
 * Persist the FSEvents id reached after a successful `index_paths` pass.
 */
public func setLastEventId(id: UInt64)  {try! rustCall() {
    uniffi_rust_core_fn_func_set_last_event_id(
        FfiConverterUInt64.lower(id),$0
    )
}
}
/**
 * Move files to Trash
 */
public func trashFiles(paths: [String]) -> FileOpResult  {
    return try!  FfiConverterTypeFileOpResult_lift(try! rustCall() {
    uniffi_rust_core_fn_func_trash_files(
        FfiConverterSequenceString.lower(paths),$0
    )
})
}
/**
 * Undo the most recent reversible, still-executed block. Returns an
 * affected_count of 0 with success=false when there's nothing to undo
 * (UI should treat that as a no-op, not an error).
 */
public func undoLastBlock() -> FileOpResult  {
    return try!  FfiConverterTypeFileOpResult_lift(try! rustCall() {
    uniffi_rust_core_fn_func_undo_last_block($0
    )
})
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_rust_core_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_rust_core_checksum_func_can_undo() != 16121) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rust_core_checksum_func_compress_files() != 27291) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rust_core_checksum_func_copy_files() != 52022) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rust_core_checksum_func_create_folder() != 32855) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rust_core_checksum_func_get_file_listing_for_ai() != 40135) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rust_core_checksum_func_get_indexed_folders() != 24405) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rust_core_checksum_func_get_recent_files() != 23640) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rust_core_checksum_func_index_paths() != 32092) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rust_core_checksum_func_last_event_id() != 15009) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rust_core_checksum_func_load_cached_index() != 15374) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rust_core_checksum_func_move_files() != 44044) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rust_core_checksum_func_needs_full_rescan() != 6768) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rust_core_checksum_func_rebuild_index() != 60778) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rust_core_checksum_func_rename_file() != 42280) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rust_core_checksum_func_search_files() != 63033) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rust_core_checksum_func_set_indexed_folders() != 59577) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rust_core_checksum_func_set_last_event_id() != 5445) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rust_core_checksum_func_trash_files() != 51150) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rust_core_checksum_func_undo_last_block() != 37958) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureRustCoreInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all